### ISSUE TITLE
How is this powered by jetbrains?

### ISSUE THREAD

**Issue by ArjixWasTaken** [Vendicated/segfault-rs#2]
Fucking read the title, lol

**Comment by Vendicated** [comment]
jetbrains ide go brrrrr

**Comment by Vendicated** [comment]
they gave me free license

**Comment by ArjixWasTaken** [comment]
Free licence bc you are a student, right?

**Comment by ArjixWasTaken** [comment]
Also, rust does not have a dedicated jetbrains IDE, it only has an extension that works on all jetbrains IDE (even the community editions), so you don't need a licence in order to use a jetbrains IDE with rust, that means the licence is irrelevant.

**Comment by ArjixWasTaken** [comment]
So unless jetbrains gave you a licence specifically for this project (which I highly doubt) this is not powered by jetbrains.

**Comment by Vendicated** [comment]
https://user-images.githubusercontent.com/45497981/212236368-8f79ee5f-d2d7-4a7f-bbb4-090ff15da067.mp4
